### ISSUE TITLE
Rust extension fails to build on stable Rust 1.86 due to rig-core using unstable let-chains

### ISSUE THREAD

**Issue by gmedrano** [open-jarvis/OpenJarvis#252]
### Description

Building the Rust extension fails on stable Rust because the transitive dependency rig-core uses unstable let-chain syntax.

This does not appear to be limited to my local machine. I verified the failure while building openjarvis_rust from this repo on stable Rust 1.86, and the errors come from rig-core source files such as providers/openrouter/streaming.rs and providers/xai/streaming.rs.

I also verified this is not limited to rig-core 0.35; 0.31.0 still contains the same unstable let-chain usage.

A temporary local workaround was to vendor rig-core and use RUSTC_BOOTSTRAP=1, but that seems like a workaround rather than the preferred long-term fix.

### Steps to Reproduce

1. From the project root, run: `uv run maturin develop -m rust/crates/openjarvis-python/Cargo.toml`
2. Observe the build failure in transitive dependency rig-core with error[E0658].

### Expected Behavior

The Rust extension should build successfully on the project’s supported stable Rust toolchain without requiring nightly Rust or bootstrap-only compiler settings.

### Actual Behavior

The build fails while compiling rig-core with error[E0658]: let expressions in this position are unstable, which prevents openjarvis_rust from being built on stable Rust 1.86.

### Operating System

macOS

### Python Version

3.12

### Hardware

Apple Silicon

### Engine

None

### Logs / Traceback

```shell
error[E0658]: let expressions in this position are unstable
--> rig-core-0.31.0/src/providers/openrouter/streaming.rs:295:24
|
295 | if let Some(finish_reason) = &choice.finish_reason && *finish_reason == FinishReason::ToolCalls {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #53667 for more information

error[E0658]: let expressions in this position are unstable
--> rig-core-0.31.0/src/providers/xai/streaming.rs:202:24
|
202 | if let StreamingCompletionChunk::Response(chunk) = data
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile rig-core due to previous errors
```
